parameters:
  - name: settings
    type: object
  - name: resource
    type: object
  - name: environment
    type: string

jobs:

  
  - ${{ if eq(parameters.resource.deployment.type, 'azureWebApp') }}:
      - template: ../../cloud/azure/appService/appService-deploy-jobs.yml
        parameters:
            settings: ${{ parameters.settings }}                  
            environment: ${{ parameters.environment }}
            resource: ${{ parameters.resource }}

      - deployment: 
        displayName: Azure dotnet Core Deployment
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: ${{ parameters.settings.azure.subscription.serviceConnection }}
                    appName: ${{ parameters.resource.name }}
                    package: $(Pipeline.Workspace)/${{ parameters.resource.alias }}/**/*.zip
