parameters:
  - name: settings
    type: object
  - name: resource
    type: object
  - name: environment
    type: string

jobs:

  
  - ${{ if eq(parameters.resource.deployment.type, 'azureWebApp') }}:
      - template: ../../cloud/azure/appService/appService-deploy-jobs.yml
        parameters:
            settings: ${{ parameters.settings }}                  
            environment: ${{ parameters.environment }}
            resource: ${{ parameters.resource }}