trigger:
  branches:
    include:
    - main
    - feature/v0.1

pool:
  vmImage: 'windows-latest'


extends: 
  template: ../../../../main.yml
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
      azureServiceConnection: $(azureServiceConnection)
      subscriptionId: $(subscriptionId)
      location: $(location)
      environments:
        - dev
        - uat
    resources:
      - name: $(resourceGroupName)
        type: resourceGroup
        enabled: true
        infrastructure:
          location: $(location)
        