trigger:
  branches:
    include:
    - main
    - feature/v0.1

pool:
  vmImage: 'windows-latest'

variables:
  - template: ./variables/dev-vars.yml

extends: 
  template: ../../../../main.yml
  parameters:
    settings:
      build:
        enabled: true
      azureServiceConnection: ServiceConnection
    resources:
      - name: RG-example
        type: resourceGroup
        enabled: true
        