trigger:
  branches:
    include:
    - main
    - feature/v0.1

pool:
  vmImage: 'windows-latest'


extends: 
  template: ../../../../main.yml
  parameters:
    settings:
      build:
        enabled: true
      azureServiceConnection: $(azureServiceConnection)
    resources:
      - name: RG-example
        type: resourceGroup
        enabled: true
        