trigger:
  branches:
    include:
    - main
    - feature/v0.1
  paths:
    include:
      - src/cloud/azure/resourceGroup/*
pool:
  vmImage: 'windows-latest'


extends: 
  template: ../../../../main.yml
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
        variablesDirectory: ./cloud/azure/keyVault/examples/variables
      azure:
        subscription:
          azureServiceConnection: $(azureServiceConnection)
          subscriptionId: $(subscriptionId)
        resourceGroup:
          name: $(resourceGroupName)
          location: $(location)
          new: true
      environments:
        - dev
        - uat
    resources:
      - name: $(resourceGroupName)
        type: resourceGroup
        enabled: true
        infrastructure:
          location: $(location)
        