parameters:
- name: settings
  type: object
- name: resource
  type: object
- name: environment
  type: string


jobs:
  - deployment: 
    displayName: Azure Web App Deployment
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            # - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
            #   inputs:
            #     source: 'current'
            #     path: '$(Pipeline.Workspace)'
            
            - powershell: |
                Write-Host "Service Connection: ${{ parameters.settings.azureServiceConnection }}"
                Write-Host "subscriptionId: ${{ parameters.settings.subscriptionId }}"
                Write-Host "location: ${{ parameters.settings.location }}"
                Write-Host "location: ${{ parameters.settings.legume }}"

                Get-ChildItem $(Pipeline.Workspace)

            # - task: AzureResourceManagerTemplateDeployment@3
            #   displayName: Creating Resource Group Infrastructure by IaC
            #   inputs:
            #     deploymentScope: 'Subscription'
            #     azureResourceManagerConnection: '${{ parameters.settings.azureServiceConnection }}'
            #     subscriptionId: ${{ parameters.settings.subscriptionId }}
            #     action: 'Create Or Update Resource Group'
            #     resourceGroupName: ${{ parameters.resource.name }}
            #     location: ${{ parameters.settings.location }}
            #     templateLocation: 'Linked artifact'
            #     csmFile: '$(Pipeline.Workspace)/${{ parameters.resource.type }}/infrastructure/azure-resourceGroup.json'
            #     overrideParameters: >
            #       -resourceGroupLocation ${{ parameters.resource.deployment.infrastructure.resourceGroupLocation }} 
            #       -resourceGroupName ${{ parameters.resource.deployment.name }} 
            #     deploymentMode: 'Incremental'
            #     deploymentOutputs: 'ArmOutputs'

        