parameters:
- name: settings
  type: object
- name: environment
  type: string


jobs:
  - deployment: resourceGroupDeploy
    displayName: Azure Resource Group Deployment
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            
            - ${{ if eq(variables['System.Debug'], 'true') }}:
              - powershell: |
                  Write-Host "Service Connection: ${{ parameters.settings.azure.subscription.azureServiceConnection }}"
                  Write-Host "subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}"
                  Write-Host "location: ${{ parameters.settings.azure.resourceGroup.location }}"
                  Write-Host "name: ${{ parameters.settings.azure.resourceGroup.name }}"

                  Get-ChildItem -Path env:
                  Get-ChildItem $(Pipeline.Workspace)
                displayName: Variables

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Creating Resource Group '${{ parameters.settings.azure.resourceGroup.name }}' by IaC
              inputs:
                deploymentScope: 'Subscription'
                azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.azureServiceConnection }}'
                subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.settings.azure.resourceGroup.name }}
                location: ${{ parameters.settings.azure.resourceGroup.location }}
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/resourceGroup/infrastructure/resourceGroup.json'
                overrideParameters: >
                  -resourceGroupLocation ${{ parameters.settings.azure.resourceGroup.location }} 
                  -resourceGroupName ${{ parameters.settings.azure.resourceGroup.name }} 
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'

        