parameters:
- name: settings
  type: object
- name: resource
  type: object
- name: environment
  type: string


jobs:
  - deployment: 
    displayName: Azure Web App Deployment
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            # - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
            #   inputs:
            #     source: 'current'
            #     path: '$(Pipeline.Workspace)'
            
            - powershell: |
                Write-Host "Service Connection: ${{ parameters.settings.azure.subscription.azureServiceConnection }}"
                Write-Host "subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}"
                Write-Host "location: ${{ parameters.settings.azure.resourceGroup.location }}"

                Get-ChildItem -Path env:
                Get-ChildItem $(Pipeline.Workspace)

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Creating Resource Group Infrastructure by IaC
              inputs:
                deploymentScope: 'Subscription'
                azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.azureServiceConnection }}'
                subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.resource.name }}
                location: ${{ parameters.settings.azure.resourceGroup.location }}
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/${{ parameters.resource.type }}/infrastructure/resourceGroup.json'
                overrideParameters: >
                  -resourceGroupLocation ${{ parameters.resource.infrastructure.location }} 
                  -resourceGroupName ${{ parameters.resource.name }} 
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'

        