parameters:
  - name: settings
    type: object
  - name: resource
    type: object

jobs:
  - job: BuildJob
    displayName: Build Job
    steps:

      - template: ../bicep/bicep-build-tasks.yml
        parameters:
          azureServiceConnection: ${{ parameters.settings.azure.subscription.azureServiceConnection }}
          bicepFilePath: $(Build.SourcesDirectory)/src/cloud/azure/resourceGroup/resourceGroup.bicep

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: ${{ parameters.resource.type }}
          publishLocation: 'pipeline'