parameters:
  - name: settings
    type: object

jobs:
  - job: resourceGroupBuildJob
    displayName: Resource Group Build Job
    steps:

      - template: ../bicep/bicep-build-tasks.yml
        parameters:
          resource: ${{ parameters.resource }}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: resourceGroup
          publishLocation: 'pipeline'