parameters:
  - name: settings
    type: object
  - name: resources
    type: object


jobs:

  - ${{ if eq(parameters.settings.azure.resourceGroup.new, 'true') }}:
    - template: ../cloud/azure/resourceGroup/resourceGroup-build-jobs.yml
      parameters:
        settings: ${{ parameters.settings }}        
  
  # call build template for each resource
  - ${{ each resource in parameters.resources }}:
    
    - ${{ if eq(resource.enabled, 'true') }}:

      - ${{ if eq(resource.type, 'keyVault') }}:
        - template: ../cloud/azure/resourceGroup/keyVault-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resource: ${{ resource }}