parameters:
  - name: settings
    type: string
  - name: resources
    type: object

jobs:

  # call build template for each resource
  - ${{ each resource in parameters.resources }}:
    
    - ${{ if eq(resource.enabled, 'true') }}:

      - ${{ if eq(resource.type, 'resourceGroup') }}:
        - template: ./../cloud/azure/resourceGroup/resourceGroup-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resource: ${{ resource }}