parameters:
  - name: settings
    type: object
  - name: resources
    type: object

jobs:

  - ${{ if eq(parameters.settings.azure.resourceGroup.new, 'true') }}:
    - template: ../cloud/azure/resourceGroup/resourceGroup-build-jobs.yml
      parameters:
        settings: ${{ parameters.settings }}        
  
  - ${{ each resource in parameters.resources }}:  

    - ${{ if eq(resource.enabled, 'true') }}:

      - ${{ if eq(resource.type, 'keyVault') }}:
        - template: ../cloud/azure/keyVault/keyVault-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}

      - ${{ if eq(resource.type, 'appService') }}:
        - template: ../cloud/azure/appService/appService-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}            

      - ${{ if eq(resource.type, 'dotnetCore') }}:
        - template: ../development/dotnetCore/dotnetCore-build-jobs.yml
          parameters:
            settings: ${{ resource }}

            