parameters:
  - name: settings
    type: object
  - name: resources
    type: object

jobs:

  # - ${{ if eq(parameters.settings.azure.resourceGroup.new, 'true') }}:
  #   - template: ../cloud/azure/resourceGroup/resourceGroup-build-jobs.yml
  #     parameters:
  #       settings: ${{ parameters.settings }}        
  
  - ${{ each res in parameters.resources }}:  
    

    - ${{ if eq(res.enabled, 'true') }}:
      - ${{ if eq(res.type, 'keyVault') }}:
        - template: ../cloud/azure/keyVault/keyVault-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resource: ${{ res }}