parameters:
  - name: resource
    type: object
jobs:
  - job:
    displayName: Azure App Service Build Job
    steps:
      - powershell: |
          Get-ChildItem -Path env:

      - template: ../bicep/bicep-build-tasks.yml
        parameters:
          resourceType: appService

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: appService
          publishLocation: 'pipeline'