parameters:
  - name: resource
    type: object
jobs:
  - job:
    displayName: IaC - Azure App Service Build Job
    steps:
      - powershell: |
          Get-ChildItem -Path env:

      - template: ../bicep/bicep-build-tasks.yml
        parameters:
          resourceType: appService
          resource: ${{ parameters.resource }}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: ${{ parameters.resource.alias }}
          publishLocation: 'pipeline'