parameters:
- name: settings
  type: object
- name: resource
  type: object  
- name: environment
  type: string


jobs:
  - deployment:
    displayName: Azure App Service Deployment
    environment: ${{ parameters.environment }}
    dependsOn: resourceGroupDeploy
    
    strategy:
      runOnce:

        ${{ if eq(parameters.settings.deploy.infrastructure.enabled, 'true') }}:
          # ${{ if eq(parameters.settings.deploy.application.enabled, 'true') }}:
          ${{ if eq(parameters.resource.deploy.application.enabled, 'true') }}:
            preDeploy:
              steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Creating App Service '${{ parameters.resource.name }}' by IaC
                  inputs:
                    azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.serviceConnection }}'
                    subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: ${{ parameters.settings.azure.resourceGroup.name }}
                    location: ${{ parameters.settings.azure.resourceGroup.location }}
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/appService/infrastructure/appService.json'
                    overrideParameters: >
                      -servicePlanName ${{ parameters.resource.deployment.infrastructure.servicePlanName }} 
                      -siteName ${{ parameters.resource.name }} 
                    deploymentMode: 'Incremental'
                    deploymentOutputs: 'ArmOutputs'

          ${{ else }}:
            deploy:
              steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Creating App Service '${{ parameters.resource.name }}' by IaC
                  inputs:
                    azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.serviceConnection }}'
                    subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: ${{ parameters.settings.azure.resourceGroup.name }}
                    location: ${{ parameters.settings.azure.resourceGroup.location }}
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/appService/infrastructure/appService.json'
                    overrideParameters: >
                      -servicePlanName ${{ parameters.resource.deployment.infrastructure.servicePlanName }} 
                      -siteName ${{ parameters.resource.name }} 
                    deploymentMode: 'Incremental'
                    deploymentOutputs: 'ArmOutputs'

        ${{ if eq(parameters.settings.deploy.application.enabled, 'true') }}:          
          ${{ if eq(parameters.resource.deploy.application.enabled, 'true') }}:
            deploy:
              steps:
          
                - ${{ if ne( parameters.resource.type, 'appService') }}:
                  - task: AzureWebApp@1
                    inputs:
                      azureSubscription: ${{ parameters.settings.azure.subscription.serviceConnection }}
                      appName: ${{ parameters.resource.name }}
                      package: $(Pipeline.Workspace)/${{ parameters.resource.alias }}/**/*.zip