parameters:
  - name: resource
    type: object
jobs:
  - job: appServiceBuildJob$(Environment.ResourceId)
    displayName: Azure App Service Build Job
    steps:

      - template: ../bicep/bicep-build-tasks.yml
        parameters:
          resourceType: appService

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: appService
          publishLocation: 'pipeline'