parameters:
  - name: settings
    type: object

jobs:
  - job: appServiceBuildJob
    displayName: Azure App Service Build Job
    steps:

      - template: ../bicep/bicep-build-tasks.yml
        parameters:
          bicepFilePath: $(Build.SourcesDirectory)/src/cloud/azure/appService/appService.bicep

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: appService
          publishLocation: 'pipeline'