trigger:
  branches:
    include:
    - main
    - feature/appService
  paths:
    include:
      - src/cloud/azure/appService/*
      
pool:
  vmImage: 'windows-latest'
  # name: default

extends: 
  template: ../../../../main.yml
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
        variablesDirectory: ./cloud/azure/appService/examples/variables
        infrastructure:
          enabled: true
        application:
          enabled: true
      azure:
        subscription:
          serviceConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
        resourceGroup:
          name: $(resourceGroupName)
          location: $(location)
          new: true
      environments:
        - dev
        # - uat
        # - prd
    resources:
      - name: $(appServiceName)
        type: appService
        enabled: true
        deployment:
          infrastructure:
            enabled: true
            servicePlanName: $(servicePlanName)
          application:
            enabled: false