resources:
  repositories:
  - repository: ReleaseEngine
    type: github
    endpoint: devopsnights
    name: devopsnights/AzureDevOpsReleaseEngine
    ref: refs/heads/feature/appService

trigger:
  branches:
    include:
    - main
    - feature/appService
  paths:
    include:
      - src/cloud/azure/appService/*
      
pool:
  vmImage: 'windows-latest'
  # name: default

extends: 
  template: /src/main.yml
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
        variablesDirectory: /src/cloud/azure/appService/examples/variables
        infrastructure:
          enabled: true
        application:
          enabled: true
      azure:
        subscription:
          serviceConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
        resourceGroup:
          name: $(resourceGroupName)
          location: $(location)
          new: true
      environments:
        - dev
        # - uat
        # - prd
    resources:
      - name: example-appService
        type: appService
        enabled: true
        deploy:
          infrastructure:
            enabled: true
            servicePlanName: $(servicePlanName)
          application:
            enabled: false