trigger:
  branches:
    include:
    - main
    - feature/v0.1
  paths:
    include:
      - src/cloud/azure/appService/*
      
pool:
  # vmImage: 'windows-latest'
  name: default

extends: 
  template: ../../../../main.yml
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
        variablesDirectory: ./cloud/azure/appService/examples/variables
      azure:
        subscription:
          azureServiceConnection: $(azureServiceConnection)
          subscriptionId: $(subscriptionId)
        resourceGroup:
          name: $(resourceGroupName)
          location: $(location)
          new: true
      environments:
        - dev
        # - uat
        # - prd
    resources:
      - name: $(appServiceName)
        type: appService
        enabled: true
        servicePlanName: $(servicePlanName)
        