parameters:
  - name: settings
    type: object
  - name: resources
    type: object

variables:
  - name: serviceConnection
    value: ServiceConnection
  - name: releaseEngineRepoName
    value: AzureDevOpsReleaseEngine
  
  - template: ./../config/config.yml

  # - ${{ if eq( variables.Build_Repository_Name, variables.releaseFrameworkRepoName) }}:
  #   - name: bicepDirectory
  #     value: $(Build.SourcesDirectory)/$(releaseEngineRepoName)/src/cloud/azure/keyVault/
  # - ${{ else }}:
  #   - name: bicepDirectory
  #     value:  $(Build.SourcesDirectory)/src/cloud/azure/keyVault/

stages:

  - ${{ if eq(parameters.settings.build.enabled, 'true') }}:
    - stage: build

      jobs:
        
        - template: ./_jobs/build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resources: ${{ parameters.resources }}

  - ${{ if eq(parameters.settings.deploy.enabled, 'true') }}:
    - ${{ each env in parameters.settings.environments }}:
      - stage: ${{ env }}
      
        variables:
          - template: ${{ parameters.settings.deploy.variablesDirectory }}/${{ env }}-vars.yml@self

        jobs:
          - template: ./_jobs/deploy-jobs.yml
            parameters:
              settings: ${{ parameters.settings }}
              resources: ${{ parameters.resources }}
              environment: ${{ env }}