parameters:
  - name: settings
    type: object
  - name: resources
    type: object

variables:
  - azureServiceConnection: ServiceConnection

stages:

  - ${{ if eq(parameters.settings.build.enabled, 'true') }}:
    - stage: build
      
      variables:
        - template: ./cloud/azure/resourceGroup/examples/variables/dev-vars.yml
      
      jobs:
        
        - template: ./_jobs/build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resources: ${{ parameters.resources }}